### ISSUE TITLE
How to memoise a function in a package

### ISSUE THREAD

**Issue by MalteThodberg** [r-lib/memoise#105]
I'm making a package with RStudio+roxygen2, and I would like to memoise a function that reads from a zipped file or URL and returns a value.

What I've tried so far (inspired from other CRAN  packages):

1) add memoise under Imports.
`usethis::use_package("memoise")`

2 )Define a function like this:
```
#' Title
#'
#' @param object value
#'
#' @return value
#' @export
hello <- memoise::memoise(function(object) {
  object + 1
})
```

3) Check and Build the package with Rstudio

4) Check if function is memoised
`> memoise::is.memoised(hello)`
[1] TRUE

5) Run an example
`> hello(2)`
[1] 3

6) Check if result is cached:
`> memoise::has_cache(hello)(2)`
[1] FALSE

So is.memoise reports the function as memoised, but it doesn't seem to cache the result.

What's the correct way of memoising a function in package in this way?

**Comment by jimhester** [comment]
I am pretty sure this works at least for the CRAN version of memoise, perhaps there is a bug in the devel version that is preventing it however.

**Comment by JosiahParry** [comment]
I too am running into this issue. Is there a vignette on using memoise with a package's function?

Edit: I believe this might be because the function that I was calling had additional function calls inside of it that themselves were not memoised. I memoised additional functions that were being called and that has seemingly resolved the issue.
